Schedule
pop-os/upgrade pull request #225
Opened 2021-11-16 14:27 UTC by mmstick

Requires `pop-system-updater` to be installed.

Requires https://github.com/pop-os/system-updater to be released.

Closes #217

2021-11-18 17:23 UTC, jacobgkau commented
This failed to build on the build server, and also fails to build locally. Seeing this on Hirsute: [upgrade-schedule-build-log.txt](https://github.com/pop-os/upgrade/files/7564738/upgrade-schedule-build-log.txt)

2021-11-18 17:31 UTC, mmstick commented
So debian vendoring of the i18n folder is borked.

2021-11-23 19:07 UTC, jacobgkau requested changes
> Requires https://github.com/pop-os/system-updater to be released.

I see that package in `master`, but it's not getting pulled in automatically with the `master` and `schedule` staging repos added. Should `pop-upgrade` depend on `pop-system-updater` now?

On 2a2d55d, this is what I see in the Settings/Upgrade page:

![Screenshot from 2021-11-23 11-59-52](https://user-images.githubusercontent.com/7199422/143087299-787227de-2d28-4599-86fd-b3075997235d.png)

- The strings for `"Automatic Updates"` and `"Automatically Install"` should not have quotation marks visible.
- When I turn `Automatic Updates` off, the `Automatically Install` line greys out, but the date/time do not change; from the mockups at https://github.com/pop-os/upgrade/issues/217, the date/time should be replaced with `Off`.
- From the mockups, midnight should be `12:00 AM`, not `00:00 AM`.
- Clicking the `Automatically Install` line is not opening up the date/time chooser dialog. I'm not seeing any messages in the terminal or journalctl when I try to do this.

2021-11-23 20:20 UTC, mmstick commented
Yes, it should definitely depend on it now.

2021-11-23 23:28 UTC, mmstick commented
GTK changes applied to pop-system-updater, which is in the cargo dependency update commit.

2021-11-29 17:19 UTC, jacobgkau commented
Still seeing `00:00 AM` on aea82f1. The dialog does open now, but it looks like the hour selector only goes from 0-11, which especially isn't normal with PM.

![Screenshot from 2021-11-29 10-16-58](https://user-images.githubusercontent.com/7199422/143913306-dda785ee-1250-484b-ab1f-c6e57c973a82.png)

2021-11-30 21:18 UTC, mmstick commented
Last commit along with having the package from last commit of pop-system-updater installed should resolve everything.

2021-12-01 17:49 UTC, 13r0ck approved these changes
All of Jacob's found bugs have been addressed. I found no other regressions.

2021-12-01 17:56 UTC, jacobgkau commented
@13r0ck Did you test updates getting installed by the timer?

2021-12-01 18:05 UTC, 13r0ck requested changes
Approval removed at request of @jacobgkau

2021-12-01 18:14 UTC, jacobgkau commented
It looks like https://github.com/pop-os/system-updater is not released yet, at least on Hirsute.

I got a dbus error in the terminal while installing it:

```
+ systemctl enable com.system76.SystemUpdater
Created symlink /etc/systemd/system/network.target.wants/com.system76.SystemUpdater.service → /lib/systemd/system/com.system76.SystemUpdater.service.
+ systemctl restart com.system76.SystemUpdater
+ systemctl --global enable com.system76.SystemUpdater.Local
Created symlink /etc/systemd/user/default.target.wants/com.system76.SystemUpdater.Local.service → /usr/lib/systemd/user/com.system76.SystemUpdater.Local.service.
+ systemctl --global restart com.system76.SystemUpdater.Local
Failed to connect to bus: $DBUS_SESSION_BUS_ADDRESS and $XDG_RUNTIME_DIR not defined (consider using --machine=<user>@.host --user to connect to bus of other user)
+ exit 0
```

It looks like it's at least attempting to install updates, but aborting instead of continuing at the apt prompt:

```
system76@pop-os:~$ sudo journalctl -u com.system76.SystemUpdater.service | tail -n 10
Dec 01 11:10:44 pop-os com.system76.SystemUpdater[7352]:   ubuntu-advantage-tools ubuntu-release-upgrader-core ufw uno-libs-private
Dec 01 11:10:44 pop-os com.system76.SystemUpdater[7352]:   update-manager-core ure usrmerge vim-common vim-tiny xxd
Dec 01 11:10:44 pop-os com.system76.SystemUpdater[7352]: 169 upgraded, 4 newly installed, 0 to remove and 0 not upgraded.
Dec 01 11:10:44 pop-os com.system76.SystemUpdater[7352]: Need to get 0 B/592 MB of archives.
Dec 01 11:10:44 pop-os com.system76.SystemUpdater[7352]: After this operation, 539 MB of additional disk space will be used.
Dec 01 11:10:44 pop-os com.system76.SystemUpdater[7352]: Do you want to continue? [Y/n] Abort.
Dec 01 11:10:44 pop-os com.system76.SystemUpdater[7359]: Reading package lists...
Dec 01 11:10:44 pop-os com.system76.SystemUpdater[7359]: Building dependency tree...
Dec 01 11:10:44 pop-os com.system76.SystemUpdater[7359]: Reading state information...
Dec 01 11:10:44 pop-os com.system76.SystemUpdater[7359]: 0 upgraded, 0 newly installed, 0 to remove and 169 not upgraded.
```

Another thing I noticed, every time I open the time/date selection dialog, it resets itself back to Monday at 1:00 AM. It should open with the time that the user had previously set.

When I'm adjusting the time, if I type in a valid hour or minute, it doesn't take effect, even after I click away. It only takes effect if I use the spinbox +/- buttons.

2021-12-06 17:20 UTC, WatchMkr commented
I'd like to change copy on one option:

Change "Available Update Notifications" to "Show Update Notifications" and remove the explanation text underneath. "requiring manual updates" could give the impression it's more technical than seeing a notification and clicking it. And the option label seems clear enough not to require additional details.

cc @maria-komarova

2022-03-11 18:24 UTC, jacobgkau commented
Typing in numbers still doesn't work-- hour/minute changes are only saved if the spinbox is used. They either need to save, or it shouldn't be possible to try and type them.

The hours/minutes do load their current values when opening the dialog now. The `Update when Available` setting does not-- if I enable it, close the dialog, and re-open the dialog, it shows as disabled (but doesn't actually get disabled unless I enable/disable it again.)

The minutes spinbox should probably show double digits even for minutes 0-9.

https://user-images.githubusercontent.com/7199422/157928103-85dfbfbe-999d-4830-917d-500f22aa0510.mp4

2022-04-05 16:23 UTC, jacobgkau commented
I am unable to install this on 22.04 due to:
```
The following packages have unmet dependencies:
 pop-system-updater : Depends: libssl1.1 but it is not installable
```
It looks like 22.04 has `libssl3` instead of `libssl1.1`.

2022-04-05 16:27 UTC, mmstick commented
I've added libssl3 to it. It should get rebuilt soon.

2022-04-05 17:29 UTC, jacobgkau requested changes
Hours and minutes are both still showing as one digit when they should be two digits.

Opening the `Automatically Install` dialog box still doesn't load the currently-saved time into the spinboxes.

![Screenshot from 2022-04-05 11-25-50](https://user-images.githubusercontent.com/7199422/161815057-800582d0-35a6-4bd6-bc75-a507aee60813.png)

If I try to change the time by typing a number and then close the dialog box without manually changing focus first, then the time doesn't save.

https://user-images.githubusercontent.com/7199422/161815097-ec90bbfc-b874-4ee7-a638-565971a9aaa5.mp4

If possible, the dialog box should check if a number was typed and apply it on exit (or just apply immediately instead of on focus change, whichever's more feasible.)

2022-04-05 17:38 UTC, jacobgkau commented
I am also seeing `Automatic Updates` keep getting turned back off after I turn it on and close/re-open Settings.

2022-04-05 17:51 UTC, mmstick commented
I can't do anything about the single digits, but I can look into the others.

2022-04-05 17:54 UTC, mmstick commented
SpinButton's signals don't seem to activate unless by a button click or focus change. So perhaps we just need to make our own SpinButton-alike widget entirely.

2022-04-05 18:56 UTC, jacobgkau commented
It sounds like that might be necessary. The mockup includes two digits for hours/minutes, and practically all clocks display time with double-digit minutes.

As for saving, if there was a save button somewhere, then having to click outside of the spinbox to save its value might be sane, but since we only have an X in the dialog, I don't think it's reasonable to expect a user to click on something other than what they're trying to change before exiting in order to have the change take effect.

2022-04-05 19:04 UTC, mmstick commented
There won't be an issue with values getting saved with a custom widget.

2022-04-06 00:52 UTC, mmstick commented
Latest update fixes packaging issues, and provides the custom spin button widget doing what we want.

2022-04-06 15:31 UTC, jacobgkau commented
I have what appears to be the latest version of both `pop-upgrade` and `pop-system-updater`, but I'm not seeing the custom spin buttons.

![Screenshot from 2022-04-06 09-30-13](https://user-images.githubusercontent.com/7199422/162011754-a0cb8347-2947-4171-8993-b3a1cfff2f98.png)

2022-04-06 15:46 UTC, mmstick commented
Ah, that's because pop-upgrade had to be updated and rebuilt. I'm testing from running `cargo run` from the GTK directory in system-updater

2022-04-06 16:54 UTC, mmstick commented
You should see this soon:

![spinbutton](https://user-images.githubusercontent.com/4143535/162026846-ab0cf0b5-13f9-4849-add8-5609a682ebf0.png)

You can watch the scheduled automatica updates being installed from:

```
journalctl -o cat -fu com.system76.SystemUpdater
```

And the session service which gives notifications when auto-updates are disabled from

```
journalctl --user -o cat -fu com.system76.SystemUpdater.Local
```

2022-04-06 17:25 UTC, jacobgkau commented
Ok, the new time selector's looking really good. When backspacing out a number, the numbers just reset to 0 instead of disappearing, which feels a little weird.

https://user-images.githubusercontent.com/7199422/162032229-f46346b3-ad81-42d8-b3a9-792082d4e81f.mp4

Would it be possible to allow actually backspacing the characters? Otherwise, pressing backspace against the 0's makes it look like I can't actually change the value of the box. For making sure the input's always valid, it could treat a single-digit entry as having a leading 0, or however you want to handle it.

Going to be testing actual upgrades/downgrades in the meantime to see how this handles some different apt scenarios in the meantime.

2022-04-06 17:26 UTC, mmstick commented
Yeah I can look into improving backspace handling

2022-04-06 17:40 UTC, jacobgkau commented
The scheduler seems to work, but I just had it skip installing an available update that `apt upgrade` shows as being available, possibly because I had a nonexistant repo configured in addition.

<details>
<summary>Output:</summary>

```
Apr 06 11:37:10 pop-os pop-system-updater[928]:  INFO pop_system_updater::service::system: initiating scheduled system update
Apr 06 11:37:10 pop-os pop-system-updater[928]:  INFO pop_system_updater::service::system: received event: AutoUpdate
Apr 06 11:37:10 pop-os pop-system-updater[928]:  INFO pop_system_updater::service::system: system update initiated
Apr 06 11:37:10 pop-os pop-system-updater[928]:  INFO pop_system_updater::package_managers::apt: performing system update with apt
Apr 06 11:37:10 pop-os pop-system-updater[928]:  INFO pop_system_updater::package_managers::apt: updating package lists
Apr 06 11:37:10 pop-os pop-system-updater[928]:  INFO pop_system_updater::package_managers::flatpak: flatpak: updating software for system
Apr 06 11:37:10 pop-os pop-system-updater[928]:  INFO pop_system_updater::package_managers::flatpak: flatpak: updating software for system76
Apr 06 11:37:10 pop-os pop-system-updater[928]:  INFO pop_system_updater::package_managers::snap: snap: updating software for system
Apr 06 11:37:10 pop-os runuser[11779]: pam_unix(runuser:session): session opened for user system76(uid=1000) by (uid=0)
Apr 06 11:37:10 pop-os pop-system-updater[11778]: Nothing to do.
Apr 06 11:37:10 pop-os pop-system-updater[11788]: Nothing unused to uninstall
Apr 06 11:37:10 pop-os pop-system-updater[928]:  INFO pop_system_updater::package_managers::flatpak: flatpak: updated software for system
Apr 06 11:37:10 pop-os pop-system-updater[11780]: Updating lvfs
Apr 06 11:37:10 pop-os pop-system-updater[11780]: Downloading?: 0%
Apr 06 11:37:10 pop-os pop-system-updater[11780]: Idle?: 100%
Apr 06 11:37:10 pop-os pop-system-updater[11780]: Idle?: 100%
Apr 06 11:37:10 pop-os pop-system-updater[11780]: Successfully downloaded new metadata: 0 local devices supported
Apr 06 11:37:10 pop-os pop-system-updater[11782]: Nothing to do.
Apr 06 11:37:10 pop-os runuser[11779]: pam_unix(runuser:session): session closed for user system76
Apr 06 11:37:10 pop-os runuser[11802]: pam_unix(runuser:session): session opened for user system76(uid=1000) by (uid=0)
Apr 06 11:37:10 pop-os pop-system-updater[11777]: Hit:1 http://apt.pop-os.org/proprietary jammy InRelease
Apr 06 11:37:10 pop-os pop-system-updater[11777]: Hit:2 http://us.archive.ubuntu.com/ubuntu jammy InRelease
Apr 06 11:37:10 pop-os pop-system-updater[11803]: Nothing unused to uninstall
Apr 06 11:37:10 pop-os pop-system-updater[11777]: Hit:3 http://apt.pop-os.org/release jammy InRelease
Apr 06 11:37:10 pop-os runuser[11802]: pam_unix(runuser:session): session closed for user system76
Apr 06 11:37:10 pop-os pop-system-updater[928]:  INFO pop_system_updater::package_managers::flatpak: flatpak: updated software for system76
Apr 06 11:37:10 pop-os pop-system-updater[11777]: Hit:4 http://us.archive.ubuntu.com/ubuntu jammy-security InRelease
Apr 06 11:37:10 pop-os pop-system-updater[11777]: Ign:5 http://apt.pop-os.org/staging/color-scheme jammy InRelease
Apr 06 11:37:10 pop-os pop-system-updater[11777]: Hit:6 http://apt.pop-os.org/staging/firefox-99.0 jammy InRelease
Apr 06 11:37:10 pop-os pop-system-updater[11777]: Hit:7 http://us.archive.ubuntu.com/ubuntu jammy-updates InRelease
Apr 06 11:37:10 pop-os pop-system-updater[11777]: Hit:8 http://apt.pop-os.org/staging/master jammy InRelease
Apr 06 11:37:10 pop-os pop-system-updater[11777]: Hit:9 http://apt.pop-os.org/staging/nvidia-510.60.02 jammy InRelease
Apr 06 11:37:10 pop-os pop-system-updater[11777]: Hit:10 http://us.archive.ubuntu.com/ubuntu jammy-backports InRelease
Apr 06 11:37:10 pop-os pop-system-updater[11777]: Hit:11 http://apt.pop-os.org/staging/schedule jammy InRelease
Apr 06 11:37:10 pop-os pop-system-updater[11777]: Hit:12 http://apt.pop-os.org/staging/screenshot-fixes jammy InRelease
Apr 06 11:37:10 pop-os pop-system-updater[11777]: Hit:13 http://apt.pop-os.org/staging/testing-desktop-widget-pr70 jammy InRelease
Apr 06 11:37:10 pop-os pop-system-updater[11777]: Hit:14 http://apt.pop-os.org/staging/workspaces-more-jammy-fixes jammy InRelease
Apr 06 11:37:10 pop-os pop-system-updater[11777]: Err:15 http://apt.pop-os.org/staging/color-scheme jammy Release
Apr 06 11:37:10 pop-os pop-system-updater[11777]:   404  Not Found [IP: 52.38.47.2 80]
Apr 06 11:37:12 pop-os pop-system-updater[11777]: Reading package lists...
Apr 06 11:37:12 pop-os pop-system-updater[11777]: E: The repository 'http://apt.pop-os.org/staging/color-scheme jammy Release' no longer has a Release file.
Apr 06 11:37:12 pop-os pop-system-updater[12594]: pop-system-updater set on hold.
Apr 06 11:37:13 pop-os pop-system-updater[12599]: Reading package lists...
Apr 06 11:37:13 pop-os pop-system-updater[12599]: Building dependency tree...
Apr 06 11:37:13 pop-os pop-system-updater[12599]: Reading state information...
Apr 06 11:37:13 pop-os pop-system-updater[12599]: 0 upgraded, 0 newly installed, 0 to remove and 1 not upgraded.
Apr 06 11:37:13 pop-os pop-system-updater[12613]: Canceled hold on pop-system-updater.
Apr 06 11:37:13 pop-os pop-system-updater[928]:  INFO pop_system_updater::package_managers::apt: apt: updated software for system
Apr 06 11:37:13 pop-os pop-system-updater[928]:  INFO pop_system_updater::service::system: system update complete
```
</pre>
</details>

Users are going to add bad repos to their systems, seems like that shouldn't be a reason not to install available updates. If it was going to block updates for this reason intentionally, then we'd need to notify the user in some way that they need to correct their configuration.

2022-04-06 18:37 UTC, mmstick commented
I've created https://github.com/pop-os/system-updater/pull/1 for tracking changes to this service and its GTK widget. It has fixes for the package list errors causing apt updates to bail, and a fix for the focusing of the entries. Still figuring out the best way the handle backspaces.

2022-04-08 16:35 UTC, mmstick commented
This last commit will have the daemon start automatically when a DBus client calls for it, instead of automatically launching on every boot. Looking into having it automatically shut down when no release update is available.

2022-04-14 00:10 UTC, mmstick commented
I've had a difficult time replicating the GDM issue but I think I've found the culprit.

2022-04-14 15:34 UTC, jacobgkau commented
> I've had a difficult time replicating the GDM issue but I think I've found the culprit.

I'm still seeing the GDM issue (stopping after login) occur with f59eff9. It has gotten less frequent, but e.g. just now I rebooted & logged in twice, and it happened the second time. (Yesterday, it was happening every single time consistently.)

2022-04-14 15:37 UTC, jacobgkau commented
Here is journalctl after booting, logging in, and seeing GDM stop. (This is before I started GDM again.) This was taken from oryp8.
[logs-after-boot-login-gdm-stop.txt](https://github.com/pop-os/upgrade/files/8490455/logs-after-boot-login-gdm-stop.txt)

Looks like there are a significant number of lines from system-updater at one point.

2022-04-14 15:46 UTC, mmstick commented
I'm seeing a handful of different errors. Will see if resolving each of them fixes it.

2022-04-14 21:07 UTC, jacobgkau commented
Things are looking promising with pop-upgrade cf2012b and pop-system-updater a11fe90. I haven't been able to recreate the GDM failure since installing those so far.

2022-04-15 15:05 UTC, n3m0-22 commented
When testing upgrading from ```20.04``` and ```21.10``` to ```22.04``` I got this error ```[ERROR] client/mod.rs:350: breaking connection to pop-upgrade daemon due to inactivity``` both from ```20.04``` to ```21.10``` and from ```21.10``` to ```22.04```. It only happens the first time running ```pop-upgrade release upgrade -f``` then everything works as expected running it a second time.

2022-04-15 15:12 UTC, mmstick commented
Looking into it. No more GDM issues though? Or system-updater problems?

2022-04-15 15:19 UTC, n3m0-22 commented
Not that I've seen so far, but I just noticed after the upgrade from ```21.10``` to ```22.04``` pop-shop now crashes and closes out when trying to install an update from it.

2022-04-15 15:21 UTC, jacobgkau commented
> Not that I've seen so far, but I just noticed after the upgrade from `21.10` to `22.04` pop-shop now crashes and closes out when trying to install an update from it.

I just performed a 21.10 to 22.04 update this morning and am not seeing this issue, so we'll need to get a little more specific than that. Do you get any terminal output about the crash if you run the Pop!_Shop from the terminal? (This would probably be a Pop!_Shop issue unless it's being caused by system-updater or something that pop-upgrade configured.)

2022-04-18 15:16 UTC, jacobgkau commented
@mmstick Can this be rebased/have conflicts resolved to include https://github.com/pop-os/upgrade/pull/277?

2022-04-18 15:22 UTC, mmstick commented
Yes

2022-04-18 17:33 UTC, jacobgkau commented
What time of the day are update notifications expected to show when automatic updates are disabled and notifications are set to Daily? Should it happen on boot/login, on repo change, or at some arbitrary time? The same question goes for Weekly and Monthly, is it the first day of the week/month?

2022-04-18 17:38 UTC, maria-komarova commented
My first inclination is to say on boot/login for daily notifications. I'm not sure I fully understand how it would work on repo change. Arbitrary time might work too, but then there is no guarantee the system will be on every time at this time. 
First day of week/month sounds good to me.

2022-04-18 17:39 UTC, mmstick commented
If the frequency is set to Daily, then it happens one day after the last update.

2022-04-18 17:42 UTC, jacobgkau commented
I saw a case where if after launching the Settings panel with automatic updates disabled, then attempting to enable them, I was unable to select a time because the `Automatically Install` line remained set to `Off`:

![Screenshot from 2022-04-18 11-34-45](https://user-images.githubusercontent.com/7199422/163849371-11de86b3-a1a5-4f71-becd-daf5827ece53.png)

I'm now seeing cases where changes I make to the enabled/disabled setting don't save after re-launching the panel:

https://user-images.githubusercontent.com/7199422/163849393-afe952d5-034b-4070-95e6-b43d1971482d.mp4

It still doesn't save as enabled if I change the time after enabling and before relaunching. I'm getting this in a terminal, assuming it's related to both issues:

```
failed to change auto-update setting: org.freedesktop.DBus.Error.ServiceUnknown: The name com.system76.SystemUpdater was not provided by any .service files
failed to change scheduling: org.freedesktop.DBus.Error.ServiceUnknown: The name com.system76.SystemUpdater was not provided by any .service files
```

I still have the `schedule` branch added and `pop-system-updater` installed at `a11fe90`, but `systemctl status pop-system-updater` says the unit's not there.

2022-04-18 17:43 UTC, jacobgkau commented
> If the frequency is set to Daily, then it happens exactly one day after the last update. Take seconds in a day and add that to the timestamp of the last update check.

What if there has never been an update check? What is the default, is it immediate when the service is started? Where is the timstamp stored?

2022-04-18 17:43 UTC, mmstick commented
I can update the session service to be better about precise timing.

2022-04-18 17:43 UTC, mmstick commented
If there hasn't been an update check then the timestamp file is missing, so it assumes that an update check is to be done.

2022-04-18 17:46 UTC, mmstick commented
And settings won't be saved if the session service / system service is not running

2022-04-18 19:49 UTC, jacobgkau commented
I tried rolling back the timestamp to more than 24 hours ago (I changed the second digit from `6` to `0` to make it `105029676`, which would be many years ago), then confirmed I have an update available with `sudo apt update`. After rebooting, the timestamp was reset to the current date/time, but I didn't see a notification from Pop!_Upgrade (just one a few minutes later which I believe was from the Pop!_Shop.) This was the log output from `com.system76.SystemUpdater.service`:

```
system76@pop-os:~$ sudo journalctl -b 0 -u com.system76.SystemUpdater.service 
[sudo] password for system76: 
Apr 18 13:35:04 pop-os systemd[1]: network-online.target: Found ordering cycle on network.target/start
Apr 18 13:35:04 pop-os systemd[1]: network-online.target: Found dependency on com.system76.SystemUpdater.service/start
Apr 18 13:35:04 pop-os systemd[1]: network-online.target: Found dependency on network-online.target/start
Apr 18 13:35:04 pop-os systemd[1]: network-online.target: Job network.target/start deleted to break ordering cycle starting with network-online.target/start
```

I changed the timestamp again and tried restarting `com.system76.SystemUpdater.service`, and the timestamp was not updated/no notification was shown; this was its log output:

```
Apr 18 13:37:38 pop-os systemd[1]: Starting Distribution updater...
Apr 18 13:37:38 pop-os pop-system-updater[7281]:  INFO pop_system_updater::service::system: initiating system service
Apr 18 13:37:38 pop-os pop-system-updater[7281]:  INFO pop_system_updater::service::system: DBus connection established
Apr 18 13:37:38 pop-os pop-system-updater[7281]:  INFO pop_system_updater::config: loading config: "/etc/pop-system-updater/config.ron"
Apr 18 13:37:38 pop-os pop-system-updater[7281]:  INFO pop_system_updater::service::system: scheduling for Schedule { interval: Monday, hour: 22, minute: 18 }
Apr 18 13:37:38 pop-os pop-system-updater[7281]:  INFO pop_system_updater::service::system: restarting any session services
Apr 18 13:37:38 pop-os systemd[1]: Started Distribution updater.
Apr 18 13:37:38 pop-os pop-system-updater[7281]:  INFO pop_system_updater::service::system: listening for events
Apr 18 13:37:38 pop-os pop-system-updater[7281]:  INFO pop_system_updater::service::system: received event: Update
Apr 18 13:37:38 pop-os pop-system-updater[7281]:  INFO pop_system_updater::service::system: checking for system updates
Apr 18 13:37:38 pop-os runuser[7301]: pam_unix(runuser:session): session opened for user system76(uid=1000) by (uid=0)
Apr 18 13:37:38 pop-os runuser[7303]: pam_unix(runuser:session): session opened for user french-user(uid=1002) by (uid=0)
Apr 18 13:37:38 pop-os runuser[7302]: pam_unix(runuser:session): session opened for user portuguese-user(uid=1001) by (uid=0)
Apr 18 13:37:38 pop-os runuser[7307]: pam_unix(runuser:session): session opened for user hong-kong-user(uid=1006) by (uid=0)
Apr 18 13:37:38 pop-os runuser[7306]: pam_unix(runuser:session): session opened for user taiwan-user(uid=1005) by (uid=0)
Apr 18 13:37:38 pop-os runuser[7304]: pam_unix(runuser:session): session opened for user chinese-user(uid=1003) by (uid=0)
Apr 18 13:37:38 pop-os runuser[7305]: pam_unix(runuser:session): session opened for user chinese-user-2(uid=1004) by (uid=0)
Apr 18 13:37:38 pop-os pop-system-updater[7308]: Failed to connect to bus: $DBUS_SESSION_BUS_ADDRESS and $XDG_RUNTIME_DIR not defined (consider using --machine=<user>@.host --user to connect to bus of other user)
Apr 18 13:37:38 pop-os pop-system-updater[7309]: Failed to connect to bus: $DBUS_SESSION_BUS_ADDRESS and $XDG_RUNTIME_DIR not defined (consider using --machine=<user>@.host --user to connect to bus of other user)
Apr 18 13:37:38 pop-os runuser[7301]: pam_unix(runuser:session): session closed for user system76
Apr 18 13:37:38 pop-os pop-system-updater[7310]: Failed to connect to bus: $DBUS_SESSION_BUS_ADDRESS and $XDG_RUNTIME_DIR not defined (consider using --machine=<user>@.host --user to connect to bus of other user)
Apr 18 13:37:38 pop-os runuser[7303]: pam_unix(runuser:session): session closed for user french-user
Apr 18 13:37:38 pop-os pop-system-updater[7311]: Failed to connect to bus: $DBUS_SESSION_BUS_ADDRESS and $XDG_RUNTIME_DIR not defined (consider using --machine=<user>@.host --user to connect to bus of other user)
Apr 18 13:37:38 pop-os runuser[7302]: pam_unix(runuser:session): session closed for user portuguese-user
Apr 18 13:37:38 pop-os pop-system-updater[7312]: Failed to connect to bus: $DBUS_SESSION_BUS_ADDRESS and $XDG_RUNTIME_DIR not defined (consider using --machine=<user>@.host --user to connect to bus of other user)
Apr 18 13:37:38 pop-os runuser[7307]: pam_unix(runuser:session): session closed for user hong-kong-user
Apr 18 13:37:38 pop-os pop-system-updater[7313]: Failed to connect to bus: $DBUS_SESSION_BUS_ADDRESS and $XDG_RUNTIME_DIR not defined (consider using --machine=<user>@.host --user to connect to bus of other user)
Apr 18 13:37:38 pop-os runuser[7306]: pam_unix(runuser:session): session closed for user taiwan-user
Apr 18 13:37:38 pop-os pop-system-updater[7314]: Failed to connect to bus: $DBUS_SESSION_BUS_ADDRESS and $XDG_RUNTIME_DIR not defined (consider using --machine=<user>@.host --user to connect to bus of other user)
Apr 18 13:37:38 pop-os runuser[7305]: pam_unix(runuser:session): session closed for user chinese-user-2
Apr 18 13:37:38 pop-os pop-system-updater[7281]:  INFO pop_system_updater::package_managers::apt: updating package lists
Apr 18 13:37:38 pop-os runuser[7304]: pam_unix(runuser:session): session closed for user chinese-user
Apr 18 13:37:38 pop-os pop-system-updater[7315]: Hit:1 http://apt.pop-os.org/proprietary jammy InRelease
Apr 18 13:37:38 pop-os pop-system-updater[7315]: Hit:2 http://us.archive.ubuntu.com/ubuntu jammy InRelease
Apr 18 13:37:38 pop-os pop-system-updater[7315]: Hit:3 http://apt.pop-os.org/release jammy InRelease
Apr 18 13:37:38 pop-os pop-system-updater[7315]: Hit:4 http://apt.pop-os.org/staging/master jammy InRelease
Apr 18 13:37:38 pop-os pop-system-updater[7315]: Hit:5 http://us.archive.ubuntu.com/ubuntu jammy-security InRelease
Apr 18 13:37:38 pop-os pop-system-updater[7315]: Hit:6 http://apt.pop-os.org/staging/nvidia-510.60.02 jammy InRelease
Apr 18 13:37:38 pop-os pop-system-updater[7315]: Hit:7 http://apt.pop-os.org/staging/schedule jammy InRelease
Apr 18 13:37:38 pop-os pop-system-updater[7315]: Hit:8 http://us.archive.ubuntu.com/ubuntu jammy-updates InRelease
Apr 18 13:37:38 pop-os pop-system-updater[7315]: Hit:9 http://apt.pop-os.org/staging/system-updater jammy InRelease
Apr 18 13:37:38 pop-os pop-system-updater[7315]: Hit:10 http://us.archive.ubuntu.com/ubuntu jammy-backports InRelease
Apr 18 13:37:38 pop-os pop-system-updater[7315]: Hit:11 http://apt.pop-os.org/staging/testing-desktop-widget-pr77 jammy InRelease
Apr 18 13:37:38 pop-os pop-system-updater[7315]: Hit:12 http://apt.pop-os.org/staging/testing-firmware-manager-pr119 jammy InRelease
Apr 18 13:37:40 pop-os pop-system-updater[7315]: Reading package lists...
Apr 18 13:37:40 pop-os pop-system-updater[7281]:  INFO pop_system_updater::service::system: check for system updates complete
```

Not sure why the timestamp's not being updated on restart since it looks like it's checking for updates, or why I'm not seeing a notification since an update is available and the timestamp is more than a day ago. I also wanted to check if the `Failed to connect to bus` log lines for each of the other user accounts on the machine are a problem.

2022-04-18 19:54 UTC, mmstick commented
Looking into it. Logs from the session service can be watched with

```
journalctl --user -fu com.system76.SystemUpdater.Local
```

2022-04-18 19:57 UTC, jacobgkau commented
> `journalctl --user -fu com.system76.SystemUpdater.Local`

Ok, restarting that user service causes the timestamp to be updated, and I see `displaying notification of available updates` in the log, but no notification.

2022-04-18 21:39 UTC, jacobgkau commented
The notification is working now:

![Screenshot from 2022-04-18 15-34-39](https://user-images.githubusercontent.com/7199422/163881599-8e77e4d2-b5ea-4a96-9f7a-a325de65bc4b.png)

I don't see the notification in the [Figma mockup I'm aware of](https://www.figma.com/proto/gtm9xOU0Y5OENwNd25Zuiw/Scheduling-and-Auto-Update-Options), was this copy approved by anyone? It says `Click here to update the system`, but clicking it doesn't install updates, it just opens the Pop!_Shop to the Installed tab and displays the list of updates. `Click here to view available updates` would be more accurate.

After clicking the notification once, every time I roll back the timestamp and restart the service again, the Pop!_Shop opens (to the Home tab) when the notification displays without me clicking the notification.

2022-04-18 21:46 UTC, mmstick commented
The pop-shop doesn't seem to respond to `io.elementary.appcenter -u` anymore when it is running in silent mode. It opens the home tab unless the appcenter is killed beforehand. But killing the appcenter will kill the application search service.

I've just copied the existing update notification.

2022-04-18 21:51 UTC, maria-komarova commented
If we want to adjust the copy of the notification (and I agree, `Click here to view available updates` seems more accurate), then we'd need to do it for all the notifications about updates. That said, I'm fine with keeping existing copy for now.

2022-04-18 21:58 UTC, jacobgkau commented
> If we want to adjust the copy of the notification (and I agree, `Click here to view available updates` seems more accurate), then we'd need to do it for all the notifications about updates.

I'm not sure I understand, what other notifications are there? Do you just mean the notifications for updates requiring manual installation in addition to the notifications for when automatic updates are completely disabled?

> That said, I'm fine with keeping existing copy for now.

What is "for now," what would we be waiting for if you agree the current wording is not accurate?

> The pop-shop doesn't seem to respond to `io.elementary.appcenter -u` anymore when it is running in silent mode. It opens the home tab unless the appcenter is killed beforehand. But killing the appcenter will kill the application search service.

Ok, so that's a pop-shop bug?

I also just had a notification fail to show on login after rolling back the timestamp and rebooting. Log output:

```
Apr 18 15:54:42 pop-os pop-system-updater[1849]:  INFO pop_system_updater::service::session: displaying notification of available updates
Apr 18 15:54:42 pop-os pop-system-updater[1849]: Backtrace omitted. Run with RUST_BACKTRACE=1 to display it.
Apr 18 15:54:42 pop-os pop-system-updater[1849]: Run with RUST_BACKTRACE=full to include source snippets.
Apr 18 15:54:42 pop-os pop-system-updater[1849]: The application panicked (crashed).
Apr 18 15:54:42 pop-os pop-system-updater[1849]:   failed to show desktop notification: Error { kind: Dbus(D-Bus error: The name org.freedesktop.Notifications was not provided by any .service files (org.freedesktop.DBus.Error.ServiceUnknown)) }
Apr 18 15:54:42 pop-os pop-system-updater[1849]: in daemon/src/notify.rs, line 16
Apr 18 15:54:42 pop-os pop-system-updater[1849]: thread: main
Apr 18 15:54:42 pop-os systemd[1840]: com.system76.SystemUpdater.Local.service: Main process exited, code=exited, status=101/n/a
Apr 18 15:54:42 pop-os systemd[1840]: com.system76.SystemUpdater.Local.service: Failed with result 'exit-code'.
```

2022-04-18 22:08 UTC, mmstick commented
Yeah, if we can get the `-u` argument to show the installed tab again, that should be resolved.

2022-04-18 22:13 UTC, maria-komarova commented
Hm.. If I think more about the copy, you don't just see available updates - you also go to the place where you install them. So if we say "Click here to update the system" that still is the end goal of the path the user initiates. So maybe that is actually better. I wonder if it could mislead people if they only see "Click here to see..." Sorry for backtracking on that one.

2022-04-18 22:15 UTC, jacobgkau commented
> Hm.. If I think more about the copy, you don't just see available updates - you also go to the place where you install them. So if we say "Click here to update the system" that still is the end goal of the path the user initiates. So maybe that is actually better. I wonder if it could mislead people if they only see "Click here to see..." Sorry for backtracking on that one.

I don't follow. I think `Click here to view available updates` implies the ability to install updates. `Click here to update the system` does not imply requiring further action.

@mmstick Do you have all the info you need about the opening by itself and/or failing to show the notification issues?

2022-04-18 22:18 UTC, mmstick commented
Yes I'm good. I've just pushed a commit to that branch which will keep trying to send that notification until the DBus notifications interface is ready.

2022-04-19 00:13 UTC, jacobgkau commented
3d0de59 is failing to build on the build server.

2022-04-19 02:26 UTC, jackpot51 approved these changes

2022-04-19 03:38 UTC, jackpot51 approved these changes

2022-04-19 18:01 UTC, mmstick commented
Will be testing a fix for 20.04 upgrades when this builds

2022-04-19 19:37 UTC, jackpot51 submitted a review, later dismissed

2022-04-19 20:12 UTC, jacobgkau commented
I was not seeing this issue before the recent fix commits, but I'm now getting `failed to fetch apt URIs to fetch` when trying to upgrade 20.04 LTS in an EFI VirtualBox VM. Steps to recreate:
- Add `schedule` and `system-updater` branches
- Run `sudo apt update`, `sudo apt upgrade`
- Reboot
- Run `pop-upgrade release upgrade -f`

This was with pop-upgrade 6587d5a and system-updater 32b8640. I also had the issue with pop-upgrade ae4b814 while 6587d5a was still building.

2022-04-19 20:13 UTC, mmstick commented
Yes it will require the latest version of the system-updater so that stopping it doesn't cause it to get restarted.

2022-04-19 20:13 UTC, jacobgkau commented
Logs: [out.txt](https://github.com/pop-os/upgrade/files/8516196/out.txt)

I see:
```
Apr 19 14:11:35 pop-os pop-upgrade[10852]: E: Error, pkgProblemResolver::Resolve generated breaks, this may be caused by held packages.
Apr 19 14:11:35 pop-os pop-upgrade[2319]: [DEBUG] daemon/mod.rs:724: status 3:6
Apr 19 14:11:35 pop-os pop-upgrade[10855]: Hit:1 http://us.archive.ubuntu.com/ubuntu jammy InRelease
Apr 19 14:11:35 pop-os pop-upgrade[10855]: Hit:2 http://apt.pop-os.org/proprietary jammy InRelease
Apr 19 14:11:35 pop-os pop-upgrade[10855]: Hit:3 http://apt.pop-os.org/release jammy InRelease
Apr 19 14:11:35 pop-os pop-upgrade[10855]: Hit:4 http://us.archive.ubuntu.com/ubuntu jammy-security InRelease
Apr 19 14:11:35 pop-os pop-upgrade[10855]: Hit:5 http://us.archive.ubuntu.com/ubuntu jammy-updates InRelease
Apr 19 14:11:36 pop-os pop-upgrade[10855]: Hit:6 http://us.archive.ubuntu.com/ubuntu jammy-backports InRelease
Apr 19 14:11:36 pop-os pop-upgrade[10855]: Reading package lists...
Apr 19 14:11:36 pop-os pop-upgrade[2319]: [DEBUG] daemon/mod.rs:724: status 3:6
Apr 19 14:11:37 pop-os pop-upgrade[2319]: [ERROR] release/mod.rs:569: failed to fetch packages: failed to fetch apt URIs to fetch: failed to exec `apt-get install --print-uris`: status is unknown: exit status: 100
```

2022-04-19 20:14 UTC, jacobgkau commented
> Yes it will require the latest version of the system-updater so that stopping it doesn't cause it to get restarted.

Got it, will wait for that.

2022-04-19 20:34 UTC, mmstick commented
Same issue. Going to just not update the package list.

2022-04-19 21:54 UTC, XV-02 commented
I'm seeing what appears to be an earlier hang up:
```
Apr 19 15:39:43 pop-os pop-upgrade[2010]: [DEBUG] daemon/mod.rs:830: Sending DBus Event: Fetching(
Apr 19 15:39:43 pop-os pop-upgrade[2010]:     "http://apt.pop-os.org/release/pool/jammy/popsicle/c61574f7d07af74cf3f67d62da1f5f538f4c7807/popsicle-gtk_1.3.0~1647358567~22.04~c61574f_amd64.deb",
Apr 19 15:39:43 pop-os pop-upgrade[2010]: )
Apr 19 15:39:43 pop-os pop-upgrade[2010]: [DEBUG] daemon/mod.rs:830: Sending DBus Event: Fetched(
Apr 19 15:39:43 pop-os pop-upgrade[2010]:     "libsensors-config_1%3a3.6.0-7ubuntu1_all.deb",
Apr 19 15:39:43 pop-os pop-upgrade[2010]:     20,
Apr 19 15:39:43 pop-os pop-upgrade[2010]:     1888,
Apr 19 15:39:43 pop-os pop-upgrade[2010]: )
Apr 19 15:39:44 pop-os pop-upgrade[2010]: [DEBUG] daemon/mod.rs:724: status 3:6
Apr 19 15:39:45 pop-os pop-upgrade[2010]: [DEBUG] daemon/mod.rs:724: status 3:6
Apr 19 15:39:46 pop-os pop-upgrade[2010]: [DEBUG] daemon/mod.rs:724: status 3:6
Apr 19 15:39:47 pop-os pop-upgrade[2010]: [DEBUG] daemon/mod.rs:724: status 3:6
Apr 19 15:39:48 pop-os pop-upgrade[2010]: [DEBUG] daemon/mod.rs:724: status 3:6
Apr 19 15:39:49 pop-os pop-upgrade[2010]: [DEBUG] daemon/mod.rs:724: status 3:6
Apr 19 15:39:50 pop-os pop-upgrade[2010]: [DEBUG] daemon/mod.rs:724: status 3:6
Apr 19 15:39:51 pop-os pop-upgrade[2010]: [DEBUG] daemon/mod.rs:724: status 3:6
Apr 19 15:39:52 pop-os pop-upgrade[2010]: [DEBUG] daemon/mod.rs:724: status 3:6
Apr 19 15:39:53 pop-os pop-upgrade[2010]: [DEBUG] daemon/mod.rs:724: status 3:6
Apr 19 15:39:54 pop-os pop-upgrade[2010]: [DEBUG] daemon/mod.rs:724: status 3:6
Apr 19 15:39:55 pop-os pop-upgrade[2010]: [DEBUG] daemon/mod.rs:724: status 3:6
Apr 19 15:39:56 pop-os pop-upgrade[2010]: [DEBUG] daemon/mod.rs:724: status 3:6
Apr 19 15:39:57 pop-os pop-upgrade[2010]: [DEBUG] daemon/mod.rs:724: status 3:6
Apr 19 15:39:58 pop-os pop-upgrade[2010]: [DEBUG] daemon/mod.rs:724: status 3:6
Apr 19 15:39:59 pop-os pop-upgrade[2010]: [DEBUG] daemon/mod.rs:724: status 3:6
Apr 19 15:40:00 pop-os pop-upgrade[2010]: [DEBUG] daemon/mod.rs:724: status 3:6
Apr 19 15:40:01 pop-os pop-upgrade[2010]: [DEBUG] daemon/mod.rs:724: status 3:6
Apr 19 15:40:02 pop-os pop-upgrade[2010]: [DEBUG] daemon/mod.rs:724: status 3:6
Apr 19 15:40:03 pop-os pop-upgrade[2010]: [DEBUG] daemon/mod.rs:724: status 3:6
Apr 19 15:40:03 pop-os pop-upgrade[2010]: [INFO ] release/mod.rs:284: popsicle-gtk_1.3.0~1647358567~22.04~c61574f_amd64.deb: retrying fetch
Apr 19 15:40:04 pop-os pop-upgrade[2010]: [DEBUG] daemon/mod.rs:724: status 3:6
```
[JCTL10c1128.txt](https://github.com/pop-os/upgrade/files/8516696/JCTL10c1128.txt)

It appears to be an issue with getting `popsicle-gtk_1.3.0~1647358567~22.04~c61574f_amd64.deb`

2022-04-19 21:55 UTC, jackpot51 approved these changes

2022-04-19 22:03 UTC, linuxgnuru commented
Pop 20.04 is getting stuck on `libtcl8.6_8.6.12+dfsg-1build1_amd64.deb`


[JCTL10c1128-2.txt](https://github.com/pop-os/upgrade/files/8516732/JCTL10c1128-2.txt)

2022-04-19 22:05 UTC, mmstick commented
It's a common issue with reqwest, so it's probably worth replacing it with isahc again.

2022-04-19 22:52 UTC, jackpot51 submitted a review, later dismissed

2022-04-19 23:56 UTC, jackpot51 approved these changes

2022-04-20 00:23 UTC, XV-02 commented
The "trying to fetch" issue is still present with `5e249f5`. I'm going to let it sit and see if it resolves at any point.

2022-04-20 00:39 UTC, jackpot51 approved these changes

2022-04-20 01:20 UTC, jacobgkau commented
The counter seems to have gone above 100% of the package number:

![image](https://user-images.githubusercontent.com/7199422/164127814-19f4ea0c-0b5a-48f8-84cd-4314c95dc036.png)

2022-04-20 01:21 UTC, jacobgkau commented
Looks like each package is being counted twice.

2022-04-20 01:26 UTC, mmstick commented
I'll increase the timeout and check that retries are getting the count reduced. 3s connection timeout might be too aggressive.

2022-04-20 01:59 UTC, jackpot51 approved these changes

2022-04-20 03:18 UTC, jacobgkau commented
Still having a numbering issue on 8bafbd0.

![image](https://user-images.githubusercontent.com/7199422/164143514-6d10e132-0c3d-4e5e-bbaa-610fe4994a42.png)

2022-04-20 03:25 UTC, jacobgkau commented
On 06937e3, the counting went as high as 4269/1806 (~2.4x the expected number). On 8bafbd0, it went to 3035/1806 (~1.7x the expected number). So 8bafbd0 seems to have helped, but not entirely resolved the issue.

Reviewing the terminal output, there were a number of packages that were listed twice in a row (with different numbers), similar to last time.

2022-04-20 12:43 UTC, jackpot51 submitted a review, later dismissed

2022-04-20 15:05 UTC, jacobgkau commented
My EFI VM upgrade is currently hanging on a package, and I noticed that the number for that package is repeating a previous number:

![image](https://user-images.githubusercontent.com/7199422/164262056-1533d9f7-bf5c-4df5-a9c5-a1afdc2c06ac.png)

2022-04-20 15:16 UTC, jacobgkau commented
Here are the logs that @jackpot51 requested: [out2.txt](https://github.com/pop-os/upgrade/files/8522818/out2.txt)

I'm seeing lots of output like this near the end, for different package names (even though the terminal output is still stuck at where it was in the screenshot):

```
Apr 20 09:13:48 pop-os pop-upgrade[2296]: [ERROR] release/mod.rs:282: thin-provisioning-tools_0.9.0-2ubuntu1_amd64.deb: fetch error: Fetch { package: "http://us.archive.ubuntu.com/ubuntu/pool/main/t/thin-provisioning-tools/thin-provisioning-tools_0.9.0-2ubuntu1_amd64.deb", source: Client(Error { kind: NameResolution, context: None, source: Some(Error { description: "Couldn't resolve host name", code: 6, extra: None }), source_type: Some("curl::error::Error"), local_addr: None, remote_addr: None }) }
Apr 20 09:13:48 pop-os pop-upgrade[2296]: [DEBUG] daemon/mod.rs:825: Sending DBus Event: Fetching(
Apr 20 09:13:48 pop-os pop-upgrade[2296]:     "http://us.archive.ubuntu.com/ubuntu/pool/main/x/xorg/xserver-xorg-input-all_7.7+23ubuntu2_amd64.deb",
Apr 20 09:13:48 pop-os pop-upgrade[2296]: )
Apr 20 09:13:51 pop-os pop-upgrade[2296]: [ERROR] lib.rs:380: retrying after error encountered: http client error
Apr 20 09:13:51 pop-os pop-upgrade[2296]: [INFO ] release/mod.rs:289: xserver-xorg-input-all_1%3a7.7+23ubuntu2_amd64.deb: retrying fetch
```

2022-04-20 15:24 UTC, mmstick commented
The current 15s timeout applies to each 8KB read from the server. If for some reason a package fails to make up to 8KB of progress in 15s it'll retry the download. There's a 3s sleep before retrying. TCP keepalive is curently disabled, TCP nodelay is disabled, only one download at a time, with a 100ms delay between each new request.

I saw a lot of curl ("Couldn't resolve host name") errors just now when downloading some packages. If that's a common issue we could have the isahc client config set to cache DNS records forever.

2022-04-20 15:36 UTC, mmstick commented
I've enabled DNS caching and TCP keep alive in this latest change. Maybe that'll fix these name resolution issues.

2022-04-20 18:30 UTC, jacobgkau commented
At nearly the same place on aa6c598, the downloads looked stuck again. There are http client errors in the logs. [out.txt](https://github.com/pop-os/upgrade/files/8524304/out.txt)

![image](https://user-images.githubusercontent.com/7199422/164298225-c99ea06b-300d-461e-bba8-0834242c307d.png)

After collecting those logs, a few more packages have been fetched (I collected them at 1218 and it's currently at 1222), but it seems like something might be off based on the logs and how slowly it's now progressing.

2022-04-20 18:43 UTC, XV-02 commented
I'm also seeing http client errors:

```
Apr 20 12:40:24 pop-os pop-upgrade[21324]: [INFO ] release/mod.rs:289: gpgconf_2.2.27-3ubuntu2_amd64.deb: retrying fetch
Apr 20 12:40:27 pop-os pop-upgrade[21324]: [ERROR] lib.rs:387: retrying after error encountered: http client error
Apr 20 12:40:27 pop-os pop-upgrade[21324]: [INFO ] release/mod.rs:289: gpgconf_2.2.27-3ubuntu2_amd64.deb: retrying fetch
Apr 20 12:40:31 pop-os pop-upgrade[21324]: [ERROR] lib.rs:387: retrying after error encountered: http client error
Apr 20 12:40:31 pop-os pop-upgrade[21324]: [INFO ] release/mod.rs:289: gpgconf_2.2.27-3ubuntu2_amd64.deb: retrying fetch
Apr 20 12:40:34 pop-os pop-upgrade[21324]: [ERROR] lib.rs:387: retrying after error encountered: http client error
Apr 20 12:40:34 pop-os pop-upgrade[21324]: [INFO ] release/mod.rs:289: gpgconf_2.2.27-3ubuntu2_amd64.deb: retrying fetch
```
[JCTLpopupgrade20042022-1.txt](https://github.com/pop-os/upgrade/files/8524471/JCTLpopupgrade20042022-1.txt)

2022-04-20 22:53 UTC, jacobgkau approved these changes
On f5ac225, I've had a successful 20.04 -> 22.04 EFI VM upgrade and a successful 21.10 -> 22.04 oryp7 w/ some non-default packages upgrade.

I have a 20.04 -> 22.04 BIOS VM w/ more comprehensive package list running, currently in the middle of downloads; I do not expect any problems with offline installation of the packages since this PR is not modifying `upgrade.sh`. (Update: 3729 packages all downloaded successfully, stopped at the correct number.)

The rest of QA has also had a number of successful upgrades. I think this is safe to approve now.

2022-04-20 23:03 UTC, merged